"""Remove column ok from user

Revision ID: 1c2fba7386d9
Revises: 860b753bc94f
Create Date: 2020-10-02 10:14:31.886425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2fba7386d9'
down_revision = '860b753bc94f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ok')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ok', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
