"""Create table user and table item

Revision ID: 31a3e1f52763
Revises: 1c2fba7386d9
Create Date: 2020-10-02 10:25:40.561377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a3e1f52763'
down_revision = '1c2fba7386d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
