"""test

Revision ID: 4a45b129656c
Revises: 68c4a87c4d3a
Create Date: 2020-10-02 09:22:47.218539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a45b129656c'
down_revision = '68c4a87c4d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
