"""test

Revision ID: 68c4a87c4d3a
Revises: fe33a847bf69
Create Date: 2020-10-01 17:21:59.130983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c4a87c4d3a'
down_revision = 'fe33a847bf69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
