"""Create user and item table

Revision ID: a21cdbf63f71
Revises: 4a45b129656c
Create Date: 2020-10-02 10:08:55.316366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21cdbf63f71'
down_revision = '4a45b129656c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
